version: '3.8'

services:
  go-data-ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-data-ingestor
    ports:
      - "5000:5000"
    env_file:
      - config.env
    restart: unless-stopped